# NAME: Shadowrocket template
# AUTHOR: Oleg Panteleev
# DESCRIPTION: all traffic through the provider, except those in the list
# REPO: https://github.com/slave-of-television/shadowrocket-config
## DEEPLINK: shadowrocket://config/add/https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/template-ios-proxy.conf
# UPDATED: 19-08-2025 19:22:19
 
[General]
bypass-system = true
ipv6 = false
prefer-ipv6 = false
private-ip-answer = true
dns-direct-system = false
dns-fallback-system = false
dns-direct-fallback-proxy = true
dns-server = https://dns.quad9.net/dns-query, https://dns.cloudflare.com/dns-query, https://dns.adguard.com/dns-query
fallback-dns-server = system
hijack-dns = :53
skip-proxy = 127.0.0.1, 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8,100.64.0.0/10,127.0.0.0/8,169.254.0.0/16,172.16.0.0/12,192.0.0.0/24,192.0.2.0/24,192.88.99.0/24,192.168.0.0/16,198.51.100.0/24,203.0.113.0/24,224.0.0.0/4,255.255.255.255/32,239.255.255.250/32
always-real-ip = time.*.com,ntp.*.com,*.cloudflareclient.com
icmp-auto-reply = false
always-reject-url-rewrite = false
udp-policy-not-supported-behaviour = REJECT

update-url = https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/template-ios-proxy.conf

[Rule]
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/my-proxy.list,PROXY  # Personal list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/google.list,PROXY    # Google list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/gemini.list,PROXY    # Google Gemini list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/openai.list,PROXY    # OpenAI list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/anthropic.list,PROXY # Anthropic list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/copilot.list,PROXY   # Microsoft Copilot list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/telegram.list,PROXY  # Telegram list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/youtube.list,PROXY   # Youtube list
RULE-SET,https://raw.githubusercontent.com/slave-of-television/shadowrocket-config/main/instagram.list,PROXY # Instagram list
FINAL,DIRECT

[Host]
localhost = 127.0.0.1

[URL Rewrite]
^(http|https):\/\/(www.)?(g|google)(\.ru|\.by) https://www.google.com 302